Create Table [User] (
UserId INT IDENTITY(1,1) PRIMARY KEY,
FullName VARCHAR(100) NOT NULL,
Email VARCHAR(150) NOT NULL UNIQUE,
PasswordHash VARCHAR(255) NOT NULL,
RoleId INT NOT NULL,
CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
CONSTRAINT FK_USER_ROLE FOREIGN KEY (RoleId) REFERENCES ROLE(RoleId)
)