Create Table Event(
EventId INT IDENTITY(1,1) PRIMARY KEY,
OrganizerId INT NOT NULL,
Name VARCHAR(150) NOT NULL,
Description VARCHAR(500) NULL,
EventDate DATETIME NOT NULL,
RouteInfo VARCHAR(600) NOT NULL,
CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
CONSTRAINT FK_Event_Organizer FOREIGN KEY (OrganizerId) REFERENCES [User] (UserId)
)